### ISSUE TITLE
ValueError when using the wavefront method in version 1.3.0

### ISSUE THREAD

**Issue by WeiliangChenOIST** [navis-org/skeletor#51]
Hello, first of all, thank you very much for developing this great module. It was a great help for my project.

Anyway, I think the wavefront solution may be broken in the latest 1.3.0 version based on my test. Here is the error message I got with the example mesh. Is there anything I can do to solve the issue? If so, please advise me.

```
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skeletor as sk
>>> mesh = sk.example_mesh()
>>> fixed = sk.pre.fix_mesh(mesh, remove_disconnected=5, inplace=False)
>>> skel = sk.skeletonize.by_wavefront(fixed, waves=1, step_size=1)
Skeletonizing: 100%|█████████████████████████████████████████████████████████████████| 6213/6213 [00:00<00:00, 210076.99it/s]
Traceback (most recent call last):
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4594, in _ensure_valid_index
    value = Series(value)
            ^^^^^^^^^^^^^
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/series.py", line 584, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/construction.py", line 659, in sanitize_array
    subarr = _sanitize_ndim(subarr, data, dtype, index, allow_2d=allow_2d)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/construction.py", line 718, in _sanitize_ndim
    raise ValueError(
ValueError: Data must be 1-dimensional, got ndarray of shape (6213, 1) instead

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/skeletor/skeletonize/wave.py", line 113, in by_wavefront
    node_radii['node_id'] = vertex_to_node_map
    ~~~~~~~~~~^^^^^^^^^^^
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/frame.py", line 5256, in _sanitize_column
    self._ensure_valid_index(value)
  File "/Users/wc/steps_venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4596, in _ensure_valid_index
    raise ValueError(
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
>>> sk.__version__
'1.3.0'
```

**Comment by schlegelp** [comment]
Thanks for reporting. I can't reproduce this on my machine yet. What version of `pandas` and `numpy` are you running?

**Comment by WeiliangChenOIST** [comment]
```
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'2.2.2'
>>> import numpy
>>> numpy.__version__
'2.0.0'
```
under MacOS 14.6.1 with python 3.12.3 from homebrew.

**Comment by schlegelp** [comment]
Ah! This seems to be some weird interaction between numpy 2.0.0 and pandas. You have two options:
1. Downgrade to numpy to `1.26.4` (the last 1.x version)
2. Upgrade numpy to 2.1.0

**Comment by WeiliangChenOIST** [comment]
Yes, that fixes the error. Thanks for the quick support.
